package gui;

import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author adam
 */
public class PhoneCallManagerFrame extends javax.swing.JFrame {

    private final CallTableModel callModel;
    private final MessageTableModel messageModel;
    
   private static final ResourceBundle texts = ResourceBundle.getBundle("i18n/texts");
    /**
     * Creates new frame PhoneCallManager
     */
    public PhoneCallManagerFrame() {
        //log.info("Starting Ponecallmanager frame");
        initComponents();
        callModel = (CallTableModel) jTableCalls.getModel();
        messageModel = (MessageTableModel) jTableMessages.getModel();
      //  TableRowSorter sorter = new TableRowSorter<CallTableModel>(callModel);
       // jTableCalls.setRowSorter(sorter);
       jTableCalls.setAutoCreateRowSorter(true);
       jTableMessages.setAutoCreateRowSorter(true);
   
       /*
       TableRowSorter<CallTableModel> sorter = new TableRowSorter<CallTableModel>(callModel);
       jTableCalls.setRowSorter(sorter);

       List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>();
       sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
       sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
       sorter.setSortKeys(sortKeys);
       */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCalls = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMessages = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(870, 500));

        jTabbedPane2.setMaximumSize(new java.awt.Dimension(850, 150));
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(850, 150));
        jTabbedPane2.setName(""); // NOI18N

        jTableCalls.setModel(new CallTableModel(callModel));
        jTableCalls.setMaximumSize(new java.awt.Dimension(800, 150));
        jTableCalls.setMinimumSize(new java.awt.Dimension(800, 150));
        jScrollPane1.setViewportView(jTableCalls);

        jTabbedPane2.addTab("Calls", jScrollPane1);

        jTableMessages.setModel(new gui.MessageTableModel(messageModel));
        jTableMessages.setMaximumSize(new java.awt.Dimension(850, 150));
        jTableMessages.setMinimumSize(new java.awt.Dimension(850, 150));
        jScrollPane2.setViewportView(jTableMessages);

        jTabbedPane2.addTab("Messages", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhoneCallManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhoneCallManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhoneCallManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhoneCallManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhoneCallManagerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableCalls;
    private javax.swing.JTable jTableMessages;
    // End of variables declaration//GEN-END:variables
}
